<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="dp_ptu_46">

  <xacro:macro name="dp_ptu_46" params="prefix plate thickness">
    <xacro:if value="${plate}">
      <link name="${prefix}ptu_base_plate_link">
        <inertial>
		  <origin rpy="0 0 0" xyz="-0.034 0 0"/>
		  <mass value="0.07"/>
		  <!-- inretia tensor for solid cuboid: m=0.07, h=0.005, w=0.142, d=0.17 -->
		  <inertia ixx="1.1777e-04" ixy="0" ixz="0" iyy="1.6873e-04" iyz="0" izz="2.8621e-04"/>
		</inertial>
		<visual>
          <origin xyz="-0.035 0 ${thickness / 2}" rpy="0 0 0"/>
          <geometry>
            <box size="0.17 0.142 ${thickness}" />
          </geometry>
          <material name="black">
            <color rgba="0.2 0.2 0.2 1"/>
          </material>
        </visual>
      </link>

      <joint name="${prefix}ptu_base_plate_joint" type="fixed">
        <parent link="${prefix}ptu_base_plate_link" />
        <child link="${prefix}ptu_base_link" />
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </joint>
    </xacro:if>

    <link name="${prefix}ptu_base_link">
    </link>

    <joint name="${prefix}ptu_base_joint" type="fixed">
      <parent link="${prefix}ptu_base_link" />
      <child link="${prefix}ptu_pan_link" />
      <origin xyz="0.0 0 ${thickness}" rpy="0 0 0" />
    </joint>

    <link name="${prefix}ptu_pan_link">
      <inertial>
		  <origin rpy="0 0 0" xyz="0 0 0.06"/>
		  <mass value="0.13"/>
		  <!-- inretia tensor for solid cuboid: m=0.13, h=0.07, w=0.046, d=0.105 -->
		  <inertia ixx="7.6006e-05" ixy="0" ixz="0" iyy="1.4136e-04" iyz="0" izz="1.7892e-04"/>
	  </inertial>
	  <visual>
        <origin xyz="0 0.0 0.025" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://dp_ptu_46_description/meshes/pan.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0.0115 0.047"/>
        <geometry>
          <box size="0.154 0.177 0.094"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}ptu_pan_joint" type="revolute">
      <parent link="${prefix}ptu_base_link" />
      <child link="${prefix}ptu_tilt_link" />
      <origin xyz="-0.00436 -0.0067 ${0.025 + thickness}" rpy="0 0 0" />
      <limit lower="-2.775" upper="2.775" effort="100.0" velocity="1.0" />
      <axis xyz="0 0 1" />
    </joint>

    <link name="${prefix}ptu_tilt_link">
      <inertial>
		  <origin rpy="0 0 0" xyz="-0.03 0 0.05"/>
		  <mass value="0.13"/>
		  <!-- inretia tensor for solid cuboid: m=0.13, h=0.07, w=0.046, d=0.105 -->
		  <inertia ixx="7.6006e-05" ixy="0" ixz="0" iyy="1.7252e-04" iyz="0" izz="1.4136e-04"/>
      </inertial>
	  <visual>
        <origin xyz="0.00436 0.0067 0.0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://dp_ptu_46_description/meshes/tilt.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0.0115 0.047"/>
        <geometry>
          <box size="0.154 0.177 0.094"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}ptu_tilt_joint" type="revolute">
      <parent link="${prefix}ptu_tilt_link" />
      <child link="${prefix}ptu_mount_link" />
      <origin xyz="0.0 0 0.0659" rpy="0 0 0" />
      <limit lower="-1.396" upper="0.541" effort="100.0" velocity="1.0" />
      <axis xyz="0 -1 0" />
    </joint>

    <link name="${prefix}ptu_mount_link">
      <visual>
        <origin xyz="0.00436 0.0067 -0.0659" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://dp_ptu_46_description/meshes/mount.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0.0115 0.047"/>
        <geometry>
          <box size="0.154 0.177 0.094"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

</robot>
