obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[0,-0.415],[-0.275, -0.215], [-0.275, 0.215],[0,0.415], [0.275, 0.215], [0.275, -0.215]]
#robot_radius: 0.17

inflation_radius: 0.3
cost_scaling_factor: 3.0

map_type: costmap
# observation_sources: scan
# scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}


observation_sources: laser_scan_sensor  point_cloud_sensor

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /phoebe/laser/scan, expected_update_rate: 0.6, observation_persistence: 0.0, marking: true, clearing: true, min_obstacle_height: -0.10, max_obstacle_height: 2.0}

point_cloud_sensor: {sensor_frame: xtion_optical_frame, data_type: PointCloud2, topic: /xtion/depth/points, expected_update_rate: 0.6, observation_persistence: 0.0, marking: true, clearing: true, min_obstacle_height: 0.08, max_obstacle_height: 2.0}

