shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
planner_frequency: 5.0
oscillation_timeout: 10.0
oscillation_distance: 0.2
# clearing_radius: 0.59
# footprint_padding: 0.015

recovery_behaviors:
  - name: 'super_conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'move_slow_and_clear'
    type: 'move_slow_and_clear/MoveSlowAndClear'

super_conservative_reset:
  reset_distance: 5.0
  layer_names: ['obstacle_layer']

conservative_reset:
  reset_distance: 3.0
  layer_names: ['obstacle_layer']

aggressive_reset:
  reset_distance: 1.84
  layer_names: ['obstacle_layer']

move_slow_and_clear:
  clearing_distance: 0.5
  limited_trans_speed: -0.15
  limited_rot_speed: 0.45
  limited_distance: 0.3

