# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_arm
  joint_model_group_pose: home_left
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - left_arm_shoulder_roll_joint
    - left_arm_shoulder_pitch_joint
    - left_arm_shoulder_yaw_joint
    - left_arm_elbow_pitch_joint
    - left_arm_elbow_yaw_joint
    - left_arm_wrist_pitch_joint
    - left_arm_wrist_roll_joint
    - left_arm_gripper_joint
    - ptu_pan_joint
    - ptu_tilt_joint
    - right_arm_shoulder_roll_joint
    - right_arm_shoulder_pitch_joint
    - right_arm_shoulder_yaw_joint
    - right_arm_elbow_pitch_joint
    - right_arm_elbow_yaw_joint
    - right_arm_wrist_pitch_joint
    - right_arm_wrist_roll_joint
    - right_arm_gripper_joint
    - wheel_front_joint
    - wheel_left_joint
    - wheel_rear_joint
    - wheel_right_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []