#goal definition
float32[2] joint_values #no goal needed for BT tick. But It could be useful to have a parameter for action (e.g.goto x,y)
---
#result definition  SUCCESS = 1, FAILURE = 0
int32 status
---
#feedback
int32 status 
