phoebe:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  # Right Arm
  right_arm_shoulder_roll_controller:
    type: position_controllers/JointPositionController
    joint: right_arm_shoulder_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}  
  right_arm_shoulder_pitch_controller:
    type: position_controllers/JointPositionController
    joint: right_arm_shoulder_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
  right_arm_shoulder_yaw_controller:
    type: position_controllers/JointPositionController
    joint: right_arm_shoulder_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
    
  right_arm_elbow_pitch_controller:
    type: position_controllers/JointPositionController
    joint: right_arm_elbow_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
    
  right_arm_elbow_yaw_controller:
    type: position_controllers/JointPositionController
    joint: right_arm_elbow_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
    
  right_arm_wrist_pitch_controller:
    type: position_controllers/JointPositionController
    joint: right_arm_wrist_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
  right_arm_wrist_roll_controller:
    type: position_controllers/JointPositionController
    joint: right_arm_wrist_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
    
  right_arm_gripper_joint_controller:
    type: position_controllers/JointPositionController
    joint: right_arm_gripper_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
  right_arm_gripper_joint2_controller:
    type: position_controllers/JointPositionController
    joint: right_arm_gripper_joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
    
  # Left Arm
  left_arm_shoulder_roll_controller:
    type: position_controllers/JointPositionController
    joint: left_arm_shoulder_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
    
  left_arm_shoulder_pitch_controller:
    type: position_controllers/JointPositionController
    joint: left_arm_shoulder_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
  left_arm_shoulder_yaw_controller:
    type: position_controllers/JointPositionController
    joint: left_arm_shoulder_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
    
  left_arm_elbow_pitch_controller:
    type: position_controllers/JointPositionController
    joint: left_arm_elbow_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
    
  left_arm_elbow_yaw_controller:
    type: position_controllers/JointPositionController
    joint: left_arm_elbow_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
    
  left_arm_wrist_pitch_controller:
    type: position_controllers/JointPositionController
    joint: left_arm_wrist_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
  left_arm_wrist_roll_controller:
    type: position_controllers/JointPositionController
    joint: left_arm_wrist_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
    
  left_arm_gripper_joint_controller:
    type: position_controllers/JointPositionController
    joint: left_arm_gripper_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
  left_arm_gripper_joint2_controller:
    type: position_controllers/JointPositionController
    joint: left_arm_gripper_joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
    
  #Wheels
  wheel_left_joint_controller:
    type: position_controllers/JointPositionController
    joint: wheel_left_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}
    
  wheel_right_joint_controller:
    type: position_controllers/JointPositionController
    joint: wheel_right_joint
    pid: {p: 1.0, i: 0.01, d: 10.0}
    
  #PTU

  ptu_pan_joint_controller:
    type: position_controllers/JointPositionController
    joint: ptu_pan_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
  ptu_tilt_joint_controller:
    type: position_controllers/JointPositionController
    joint: ptu_tilt_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}  
    
    
    


  